 phala-pruntime:
   image: ${PRUNTIME_IMAGE}
   container_name: phala-pruntime
   hostname: phala-pruntime
   ports:
    - "8000:8000"
   devices:
    - /dev/sgx_enclave:/dev/sgx/enclave
    - /dev/sgx_provision:/dev/sgx/provision
   environment:
    - EXTRA_OPTS=--cores=${CORES}
    - ROCKET_ADDRESS=0.0.0.0
   volumes:
    - ${PRUNTIME_VOLUMES}

